"""Canonical receiver payload manifest for scaffold and inspection."""

from __future__ import annotations

from dataclasses import dataclass

CORE_RECEIVER_PAYLOAD_MANIFEST_NAME = "core-local-install"


@dataclass(frozen=True)
class ReceiverPayloadEntry:
    """One receiver file's source, write, and inspection contract."""

    path: str
    classes: tuple[str, ...]
    source: str
    content_kind: str
    write_policy: str
    comparison_kind: str
    conflict_handling: str
    scaffold_order: int
    inspection_order: int
    fresh_receiver_status: str = "missing"
    fresh_receiver_action: str = "create"


RECEIVER_PAYLOAD_MANIFEST: tuple[ReceiverPayloadEntry, ...] = (
    ReceiverPayloadEntry(
        "AGENTS.md",
        ("templated", "inspected", "receiver-owned"),
        "Canonical SDF Front Door bridge block",
        "generated",
        "write-if-absent",
        "bridge",
        "report-missing-bridge",
        8,
        0,
    ),
    ReceiverPayloadEntry(
        "CLAUDE.md",
        ("templated", "inspected", "receiver-owned"),
        "Canonical SDF Claude activation bridge",
        "generated",
        "write-if-absent",
        "claude-bridge",
        "report-missing-bridge",
        9,
        1,
    ),
    ReceiverPayloadEntry(
        ".gitattributes",
        ("inspected", "receiver-owned", "shared"),
        "SDF evidence generated-file attribute",
        "shared",
        "create-or-append-exact-rule",
        "gitattributes",
        "append-missing-rule",
        10,
        2,
    ),
    ReceiverPayloadEntry(
        ".gitignore",
        ("inspected", "receiver-owned", "shared"),
        "SDF handoff local-artifact ignore rule",
        "shared",
        "create-or-append-exact-rule",
        "gitignore",
        "append-missing-rule",
        11,
        3,
    ),
    ReceiverPayloadEntry(
        ".sdf/agent-instructions.md",
        ("copied", "receiver-owned"),
        "Portable SDF agent instructions approved for receiver use",
        "portable",
        "write-if-absent",
        "exact",
        "report-conflict",
        1,
        4,
    ),
    ReceiverPayloadEntry(
        ".sdf/config.yml",
        ("generated", "receiver-owned"),
        "Minimal receiver config generated by SDF CLI",
        "generated",
        "write-if-absent",
        "config",
        "report-conflict",
        0,
        5,
    ),
    ReceiverPayloadEntry(
        ".sdf/standard-sdf-non-claims.md",
        ("copied", "receiver-owned"),
        "Portable SDF standard non-claims boundary",
        "portable",
        "write-if-absent",
        "exact",
        "report-conflict",
        2,
        6,
    ),
    ReceiverPayloadEntry(
        ".sdf/verification.yml",
        ("generated", "receiver-owned"),
        "Receiver verification placeholder generated by SDF CLI",
        "generated",
        "write-if-absent",
        "shape-only",
        "preserve-receiver-content",
        3,
        7,
    ),
    ReceiverPayloadEntry(
        ".sdf/contracts/evidence-archive.md",
        ("copied", "receiver-owned"),
        "Portable SDF evidence archive contract",
        "portable",
        "write-if-absent",
        "exact",
        "report-conflict",
        4,
        8,
    ),
    ReceiverPayloadEntry(
        ".sdf/contracts/verification-config.md",
        ("copied", "receiver-owned"),
        "Portable SDF verification config contract",
        "portable",
        "write-if-absent",
        "exact",
        "report-conflict",
        5,
        9,
    ),
    ReceiverPayloadEntry(
        ".sdf/playbooks/governed-change-loop.md",
        ("copied", "receiver-owned"),
        "Portable SDF governed change loop playbook",
        "portable",
        "write-if-absent",
        "exact",
        "report-conflict",
        6,
        10,
    ),
)


def receiver_payload_entry(path: str) -> ReceiverPayloadEntry:
    """Return the canonical payload entry for one receiver-relative path."""

    for entry in RECEIVER_PAYLOAD_MANIFEST:
        if entry.path == path:
            return entry
    raise KeyError(path)


def scaffold_receiver_payload_entries() -> tuple[ReceiverPayloadEntry, ...]:
    """Return canonical entries in the established scaffold output order."""

    return tuple(
        sorted(RECEIVER_PAYLOAD_MANIFEST, key=lambda item: item.scaffold_order)
    )


def inspection_receiver_payload_entries() -> tuple[ReceiverPayloadEntry, ...]:
    """Return canonical entries in the established inspection output order."""

    return tuple(
        sorted(RECEIVER_PAYLOAD_MANIFEST, key=lambda item: item.inspection_order)
    )
